export type RegionalFood = {
  nameAr: string;
  nameEn: string;
  country: string;
  calories100g: number;
  protein100g: number;
  carbs100g: number;
  fat100g: number;
  source: string;
  confidence: number;
  note: string;
};

/**
 * Offline regional core.
 *
 * This is intentionally a small, original reference layer rather than a copy
 * of a third-party database. It gives the app useful Middle-East foods when
 * offline or when a remote source has no match. Remote/official sources should
 * win whenever they return a product.
 */
export const REGIONAL_CORE: RegionalFood[] = [
  {
    "nameAr": "كبسة دجاج",
    "nameEn": "Chicken Kabsa",
    "country": "sa",
    "calories100g": 205,
    "protein100g": 15,
    "carbs100g": 14,
    "fat100g": 9,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "كبسة لحم",
    "nameEn": "Lamb Kabsa",
    "country": "sa",
    "calories100g": 225,
    "protein100g": 14,
    "carbs100g": 14,
    "fat100g": 12,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مندي دجاج",
    "nameEn": "Chicken Mandi",
    "country": "sa",
    "calories100g": 195,
    "protein100g": 14.5,
    "carbs100g": 14,
    "fat100g": 8.2,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مندي لحم",
    "nameEn": "Lamb Mandi",
    "country": "sa",
    "calories100g": 235,
    "protein100g": 14,
    "carbs100g": 13,
    "fat100g": 13,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مضغوط دجاج",
    "nameEn": "Chicken Madhbi/Madghout",
    "country": "sa",
    "calories100g": 205,
    "protein100g": 15,
    "carbs100g": 13,
    "fat100g": 9,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "جريش",
    "nameEn": "Jareesh",
    "country": "sa",
    "calories100g": 145,
    "protein100g": 6,
    "carbs100g": 18,
    "fat100g": 5,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "قرصان",
    "nameEn": "Qursan",
    "country": "sa",
    "calories100g": 165,
    "protein100g": 6,
    "carbs100g": 25,
    "fat100g": 4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مرقوق",
    "nameEn": "Marqooq",
    "country": "sa",
    "calories100g": 170,
    "protein100g": 7,
    "carbs100g": 24,
    "fat100g": 5,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مطازيز",
    "nameEn": "Matazeez",
    "country": "sa",
    "calories100g": 175,
    "protein100g": 8,
    "carbs100g": 22,
    "fat100g": 6,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "سليق",
    "nameEn": "Saleeg",
    "country": "sa",
    "calories100g": 150,
    "protein100g": 6,
    "carbs100g": 19,
    "fat100g": 5,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مرق لحم",
    "nameEn": "Meat Marag",
    "country": "sa",
    "calories100g": 120,
    "protein100g": 7,
    "carbs100g": 5,
    "fat100g": 7,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مطازيز لحم",
    "nameEn": "Matazeez with meat",
    "country": "sa",
    "calories100g": 190,
    "protein100g": 9,
    "carbs100g": 21,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "هريس",
    "nameEn": "Harees",
    "country": "sa",
    "calories100g": 145,
    "protein100g": 7,
    "carbs100g": 20,
    "fat100g": 4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "ثريد",
    "nameEn": "Thareed",
    "country": "sa",
    "calories100g": 150,
    "protein100g": 8,
    "carbs100g": 20,
    "fat100g": 4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مقلقل لحم",
    "nameEn": "Lamb Mogalgal",
    "country": "sa",
    "calories100g": 220,
    "protein100g": 20,
    "carbs100g": 4,
    "fat100g": 14,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مقلقل دجاج",
    "nameEn": "Chicken Mogalgal",
    "country": "sa",
    "calories100g": 180,
    "protein100g": 23,
    "carbs100g": 5,
    "fat100g": 7,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "سمك صيادية",
    "nameEn": "Sayadiyah fish",
    "country": "sa",
    "calories100g": 175,
    "protein100g": 20,
    "carbs100g": 16,
    "fat100g": 4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "رز بشاور مطبوخ",
    "nameEn": "Bashawar rice cooked",
    "country": "sa",
    "calories100g": 145,
    "protein100g": 3,
    "carbs100g": 30,
    "fat100g": 1,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "رز بسمتي مطبوخ",
    "nameEn": "Basmati rice cooked",
    "country": "sa",
    "calories100g": 130,
    "protein100g": 2.7,
    "carbs100g": 28.2,
    "fat100g": 0.3,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "تمر سكري",
    "nameEn": "Sukkari dates",
    "country": "sa",
    "calories100g": 282,
    "protein100g": 2.7,
    "carbs100g": 79.7,
    "fat100g": 0.4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "تمر خلاص",
    "nameEn": "Khalas dates",
    "country": "sa",
    "calories100g": 275,
    "protein100g": 2.5,
    "carbs100g": 73,
    "fat100g": 0.4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "قهوة عربية",
    "nameEn": "Arabic coffee",
    "country": "sa",
    "calories100g": 3,
    "protein100g": 0.1,
    "carbs100g": 0.5,
    "fat100g": 0.1,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "لبن كامل الدسم",
    "nameEn": "Full-fat laban",
    "country": "sa",
    "calories100g": 61,
    "protein100g": 3.2,
    "carbs100g": 4.8,
    "fat100g": 3.3,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "لبن قليل الدسم",
    "nameEn": "Low-fat laban",
    "country": "sa",
    "calories100g": 45,
    "protein100g": 3.3,
    "carbs100g": 5,
    "fat100g": 1.2,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "زبادي كامل الدسم",
    "nameEn": "Full-fat yogurt",
    "country": "sa",
    "calories100g": 61,
    "protein100g": 3.5,
    "carbs100g": 4.7,
    "fat100g": 3.3,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "خبز تميس",
    "nameEn": "Tamees bread",
    "country": "sa",
    "calories100g": 270,
    "protein100g": 8,
    "carbs100g": 51,
    "fat100g": 4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "خبز صامولي",
    "nameEn": "Samoli bread",
    "country": "sa",
    "calories100g": 270,
    "protein100g": 9,
    "carbs100g": 49,
    "fat100g": 4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "خبز عربي",
    "nameEn": "Arabic pita bread",
    "country": "sa",
    "calories100g": 275,
    "protein100g": 9.1,
    "carbs100g": 55.7,
    "fat100g": 1.2,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "فول مدمس",
    "nameEn": "Foul medames",
    "country": "eg",
    "calories100g": 110,
    "protein100g": 7.6,
    "carbs100g": 19.7,
    "fat100g": 0.4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "طعمية مصرية",
    "nameEn": "Egyptian falafel",
    "country": "eg",
    "calories100g": 333,
    "protein100g": 13.3,
    "carbs100g": 31.8,
    "fat100g": 17.8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "كشري",
    "nameEn": "Koshari",
    "country": "eg",
    "calories100g": 165,
    "protein100g": 5.5,
    "carbs100g": 29,
    "fat100g": 3,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "ملوخية",
    "nameEn": "Molokhia",
    "country": "eg",
    "calories100g": 75,
    "protein100g": 3,
    "carbs100g": 8,
    "fat100g": 3,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "فول بالزيت",
    "nameEn": "Foul with oil",
    "country": "eg",
    "calories100g": 145,
    "protein100g": 6.5,
    "carbs100g": 18,
    "fat100g": 5.5,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "فول بالبيض",
    "nameEn": "Foul with egg",
    "country": "eg",
    "calories100g": 150,
    "protein100g": 8,
    "carbs100g": 13,
    "fat100g": 7,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مسقعة مصرية",
    "nameEn": "Egyptian moussaka",
    "country": "eg",
    "calories100g": 125,
    "protein100g": 4,
    "carbs100g": 10,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "فتة مصرية",
    "nameEn": "Egyptian fatta",
    "country": "eg",
    "calories100g": 180,
    "protein100g": 8,
    "carbs100g": 18,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "فتة شاورما",
    "nameEn": "Shawarma fatta",
    "country": "eg",
    "calories100g": 210,
    "protein100g": 12,
    "carbs100g": 18,
    "fat100g": 10,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "محشي كرنب",
    "nameEn": "Stuffed cabbage leaves",
    "country": "eg",
    "calories100g": 145,
    "protein100g": 4,
    "carbs100g": 19,
    "fat100g": 6,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "محشي ورق عنب",
    "nameEn": "Stuffed vine leaves",
    "country": "eg",
    "calories100g": 155,
    "protein100g": 3,
    "carbs100g": 20,
    "fat100g": 6,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "محشي كوسة",
    "nameEn": "Stuffed zucchini",
    "country": "eg",
    "calories100g": 125,
    "protein100g": 4,
    "carbs100g": 15,
    "fat100g": 5,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "ملوخية بالأرانب",
    "nameEn": "Molokhia with rabbit",
    "country": "eg",
    "calories100g": 120,
    "protein100g": 15,
    "carbs100g": 7,
    "fat100g": 4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "فتة لحمة",
    "nameEn": "Beef fatta",
    "country": "eg",
    "calories100g": 205,
    "protein100g": 12,
    "carbs100g": 18,
    "fat100g": 10,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "شاورما فراخ",
    "nameEn": "Chicken shawarma",
    "country": "eg",
    "calories100g": 215,
    "protein100g": 20,
    "carbs100g": 5,
    "fat100g": 13,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "شاورما لحم",
    "nameEn": "Beef shawarma",
    "country": "eg",
    "calories100g": 240,
    "protein100g": 20,
    "carbs100g": 5,
    "fat100g": 16,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "كبدة اسكندراني",
    "nameEn": "Alexandrian liver",
    "country": "eg",
    "calories100g": 185,
    "protein100g": 22,
    "carbs100g": 6,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "فطير مشلتت",
    "nameEn": "Feteer meshaltet",
    "country": "eg",
    "calories100g": 390,
    "protein100g": 7,
    "carbs100g": 43,
    "fat100g": 22,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "بسبوسة",
    "nameEn": "Basbousa",
    "country": "eg",
    "calories100g": 360,
    "protein100g": 4,
    "carbs100g": 55,
    "fat100g": 14,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "أم علي",
    "nameEn": "Om Ali",
    "country": "eg",
    "calories100g": 250,
    "protein100g": 6,
    "carbs100g": 31,
    "fat100g": 11,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "كنافة",
    "nameEn": "Kunafa",
    "country": "eg",
    "calories100g": 350,
    "protein100g": 7,
    "carbs100g": 46,
    "fat100g": 16,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "لقمة القاضي",
    "nameEn": "Luqaimat",
    "country": "eg",
    "calories100g": 350,
    "protein100g": 5,
    "carbs100g": 48,
    "fat100g": 16,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "حمص",
    "nameEn": "Hummus",
    "country": "lb",
    "calories100g": 166,
    "protein100g": 7.9,
    "carbs100g": 14.3,
    "fat100g": 9.6,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "تبولة",
    "nameEn": "Tabbouleh",
    "country": "lb",
    "calories100g": 90,
    "protein100g": 3,
    "carbs100g": 10,
    "fat100g": 4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "فتوش",
    "nameEn": "Fattoush",
    "country": "lb",
    "calories100g": 110,
    "protein100g": 3,
    "carbs100g": 12,
    "fat100g": 6,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "متبل باذنجان",
    "nameEn": "Baba ghanoush",
    "country": "lb",
    "calories100g": 120,
    "protein100g": 3,
    "carbs100g": 8,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "ورق عنب",
    "nameEn": "Grape leaves stuffed",
    "country": "lb",
    "calories100g": 155,
    "protein100g": 3,
    "carbs100g": 20,
    "fat100g": 6,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "كبة مقلية",
    "nameEn": "Fried kibbeh",
    "country": "lb",
    "calories100g": 280,
    "protein100g": 12,
    "carbs100g": 18,
    "fat100g": 17,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "كبة مشوية",
    "nameEn": "Grilled kibbeh",
    "country": "lb",
    "calories100g": 220,
    "protein100g": 14,
    "carbs100g": 18,
    "fat100g": 11,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "كبة لبنية",
    "nameEn": "Kibbeh labanieh",
    "country": "lb",
    "calories100g": 170,
    "protein100g": 11,
    "carbs100g": 14,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مناقيش زعتر",
    "nameEn": "Manakish zaatar",
    "country": "lb",
    "calories100g": 290,
    "protein100g": 8,
    "carbs100g": 38,
    "fat100g": 12,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مناقيش جبنة",
    "nameEn": "Cheese manakish",
    "country": "lb",
    "calories100g": 315,
    "protein100g": 12,
    "carbs100g": 35,
    "fat100g": 14,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "فلافل شامية",
    "nameEn": "Levantine falafel",
    "country": "lb",
    "calories100g": 333,
    "protein100g": 13,
    "carbs100g": 32,
    "fat100g": 18,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "شاورما دجاج عربي",
    "nameEn": "Levant chicken shawarma",
    "country": "lb",
    "calories100g": 215,
    "protein100g": 20,
    "carbs100g": 7,
    "fat100g": 12,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "شاورما لحم عربي",
    "nameEn": "Levant beef shawarma",
    "country": "lb",
    "calories100g": 250,
    "protein100g": 19,
    "carbs100g": 6,
    "fat100g": 17,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "فتة حمص",
    "nameEn": "Hummus fatta",
    "country": "lb",
    "calories100g": 175,
    "protein100g": 7,
    "carbs100g": 18,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "فتة باذنجان",
    "nameEn": "Eggplant fatta",
    "country": "lb",
    "calories100g": 165,
    "protein100g": 5,
    "carbs100g": 17,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مجدرة",
    "nameEn": "Mujaddara",
    "country": "lb",
    "calories100g": 155,
    "protein100g": 6,
    "carbs100g": 25,
    "fat100g": 3,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مسخن دجاج",
    "nameEn": "Musakhan",
    "country": "jo",
    "calories100g": 210,
    "protein100g": 14,
    "carbs100g": 15,
    "fat100g": 10,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "منسف لحم",
    "nameEn": "Mansaf",
    "country": "jo",
    "calories100g": 235,
    "protein100g": 15,
    "carbs100g": 14,
    "fat100g": 12,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مقلوبة",
    "nameEn": "Maqluba",
    "country": "jo",
    "calories100g": 185,
    "protein100g": 10,
    "carbs100g": 18,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "فلافل أردنية",
    "nameEn": "Jordanian falafel",
    "country": "jo",
    "calories100g": 330,
    "protein100g": 13,
    "carbs100g": 31,
    "fat100g": 18,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "شوربة عدس",
    "nameEn": "Lentil soup",
    "country": "jo",
    "calories100g": 90,
    "protein100g": 5,
    "carbs100g": 14,
    "fat100g": 1.5,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مكبوس دجاج",
    "nameEn": "Chicken machboos",
    "country": "kw",
    "calories100g": 205,
    "protein100g": 14,
    "carbs100g": 15,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مكبوس لحم",
    "nameEn": "Lamb machboos",
    "country": "kw",
    "calories100g": 230,
    "protein100g": 14,
    "carbs100g": 15,
    "fat100g": 12,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مموش",
    "nameEn": "Mumawwash",
    "country": "kw",
    "calories100g": 160,
    "protein100g": 6,
    "carbs100g": 25,
    "fat100g": 3,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "هريس كويتي",
    "nameEn": "Kuwaiti harees",
    "country": "kw",
    "calories100g": 145,
    "protein100g": 7,
    "carbs100g": 20,
    "fat100g": 4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مجبوس سمك",
    "nameEn": "Fish machboos",
    "country": "kw",
    "calories100g": 190,
    "protein100g": 18,
    "carbs100g": 18,
    "fat100g": 5,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مكبوس دجاج كويتي",
    "nameEn": "Kuwaiti chicken machboos",
    "country": "kw",
    "calories100g": 205,
    "protein100g": 14,
    "carbs100g": 15,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "قبولي",
    "nameEn": "Kabuli rice",
    "country": "om",
    "calories100g": 165,
    "protein100g": 4,
    "carbs100g": 29,
    "fat100g": 3,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "عرسية",
    "nameEn": "Arsiyah",
    "country": "om",
    "calories100g": 145,
    "protein100g": 7,
    "carbs100g": 20,
    "fat100g": 4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مكبوس عماني",
    "nameEn": "Omani majboos",
    "country": "om",
    "calories100g": 205,
    "protein100g": 14,
    "carbs100g": 15,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "شواء عماني",
    "nameEn": "Omani shuwa",
    "country": "om",
    "calories100g": 240,
    "protein100g": 23,
    "carbs100g": 2,
    "fat100g": 15,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مضروبة",
    "nameEn": "Madhrouba",
    "country": "qa",
    "calories100g": 150,
    "protein100g": 8,
    "carbs100g": 18,
    "fat100g": 5,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مجبوس قطري",
    "nameEn": "Qatari machboos",
    "country": "qa",
    "calories100g": 205,
    "protein100g": 14,
    "carbs100g": 15,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "ثريد قطري",
    "nameEn": "Qatari thareed",
    "country": "qa",
    "calories100g": 155,
    "protein100g": 8,
    "carbs100g": 20,
    "fat100g": 5,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "صالونة دجاج",
    "nameEn": "Chicken salona",
    "country": "qa",
    "calories100g": 110,
    "protein100g": 12,
    "carbs100g": 8,
    "fat100g": 4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "مجبوس بحريني",
    "nameEn": "Bahraini machboos",
    "country": "bh",
    "calories100g": 205,
    "protein100g": 14,
    "carbs100g": 15,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "هريس بحريني",
    "nameEn": "Bahraini harees",
    "country": "bh",
    "calories100g": 145,
    "protein100g": 7,
    "carbs100g": 20,
    "fat100g": 4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "ثريد بحريني",
    "nameEn": "Bahraini thareed",
    "country": "bh",
    "calories100g": 155,
    "protein100g": 8,
    "carbs100g": 20,
    "fat100g": 5,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "كسكس بالخضار",
    "nameEn": "Vegetable couscous",
    "country": "ma",
    "calories100g": 120,
    "protein100g": 4,
    "carbs100g": 22,
    "fat100g": 2,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "كسكس بالدجاج",
    "nameEn": "Chicken couscous",
    "country": "ma",
    "calories100g": 170,
    "protein100g": 10,
    "carbs100g": 22,
    "fat100g": 5,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "طاجين دجاج",
    "nameEn": "Chicken tagine",
    "country": "ma",
    "calories100g": 155,
    "protein100g": 15,
    "carbs100g": 7,
    "fat100g": 7,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "طاجين لحم",
    "nameEn": "Beef tagine",
    "country": "ma",
    "calories100g": 190,
    "protein100g": 16,
    "carbs100g": 9,
    "fat100g": 10,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "حريرة",
    "nameEn": "Harira soup",
    "country": "ma",
    "calories100g": 85,
    "protein100g": 5,
    "carbs100g": 11,
    "fat100g": 2,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "بسطيلة دجاج",
    "nameEn": "Chicken pastilla",
    "country": "ma",
    "calories100g": 290,
    "protein100g": 13,
    "carbs100g": 25,
    "fat100g": 15,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "رفيسة",
    "nameEn": "Rfissa",
    "country": "ma",
    "calories100g": 210,
    "protein100g": 13,
    "carbs100g": 19,
    "fat100g": 9,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "شخشوخة",
    "nameEn": "Chakhchoukha",
    "country": "dz",
    "calories100g": 175,
    "protein100g": 8,
    "carbs100g": 24,
    "fat100g": 6,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "كسكس جزائري",
    "nameEn": "Algerian couscous",
    "country": "dz",
    "calories100g": 150,
    "protein100g": 5,
    "carbs100g": 25,
    "fat100g": 3,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "طاجين جزائري",
    "nameEn": "Algerian tajine",
    "country": "dz",
    "calories100g": 175,
    "protein100g": 13,
    "carbs100g": 8,
    "fat100g": 9,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "شوربة فريك",
    "nameEn": "Freekeh soup",
    "country": "dz",
    "calories100g": 95,
    "protein100g": 4,
    "carbs100g": 14,
    "fat100g": 2,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "ملوخية تونسية",
    "nameEn": "Tunisian molokhia",
    "country": "tn",
    "calories100g": 130,
    "protein100g": 8,
    "carbs100g": 7,
    "fat100g": 8,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "كسكسي تونسي",
    "nameEn": "Tunisian couscous",
    "country": "tn",
    "calories100g": 160,
    "protein100g": 6,
    "carbs100g": 24,
    "fat100g": 4,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "لبلابي",
    "nameEn": "Lablabi",
    "country": "tn",
    "calories100g": 105,
    "protein100g": 5,
    "carbs100g": 15,
    "fat100g": 2,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "بريك",
    "nameEn": "Brik",
    "country": "tn",
    "calories100g": 260,
    "protein100g": 9,
    "carbs100g": 23,
    "fat100g": 14,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  },
  {
    "nameAr": "شوربة فريك تونسية",
    "nameEn": "Tunisian frik soup",
    "country": "tn",
    "calories100g": 90,
    "protein100g": 5,
    "carbs100g": 13,
    "fat100g": 2,
    "source": "Health OS Regional Core",
    "confidence": 0.68,
    "note": "قيم إرشادية للطبق لكل 100 جم؛ الوصفة/الزيت/الحجم قد يغيّر القيم"
  }
];
